version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: yahiakr/ecommerce-reverseproxy

  users-microservice:
    build:
      context: ../../users-microservice
    image: yahiakr/ecommerce-users-microservice


  products-microservice:
    build:
      context: ../../products-microservice
    image: yahiakr/ecommerce-products-microservice

  orders-microservice:
    build:
      context: ../../orders-microservice
    image: yahiakr/ecommerce-orders-microservice
  
  admin-frontend:
    build:
      context: ../../admin-frontend
    image: yahiakr/ecommerce-admin-frontend

  client-frontend:
    build:
      context: ../../client-frontend
    image: yahiakr/ecommerce-client-frontend
