apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: admin-frontend
  name: admin-frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: admin-frontend
        api: external        
    spec:
      containers:
      - image: yahiakr/ecommerce-admin-frontend
        name: admin-frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always