apiVersion: v1
kind: Service
metadata:
  labels:
    service: client-frontend
  name: client-frontend
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  selector:
    service: client-frontend
#  type: LoadBalancer   