apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: client-frontend
  name: client-frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: client-frontend
        api: external
    spec:
      containers:
      - image: yahiakr/ecommerce-client-frontend
        name: client-frontend
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always