apiVersion: v1
kind: Service
metadata:
  labels:
    service: users-microservice
  name: users-microservice
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: users-microservice